### ISSUE TITLE
rake aborded

### ISSUE THREAD

**Issue by phistep** [danlucraft/git.js#1]
When I try to use

```
$ rake demo
```

I get 

```
~/test/node/git.js$ rake demo --trace
(in /home/ps0ke/test/node/git.js)
** Invoke demo (first_time)
** Invoke package_client (first_time)
** Execute package_client
packaged lib/git.min.js
** Execute demo
rake aborted!
No such file or directory - thin -R demos/config.ru -p 9292 start
/home/ps0ke/test/node/git.js/Rakefile:33:in `exec'
/home/ps0ke/test/node/git.js/Rakefile:33
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
```

I just fetched your repo and so I am for sure on the latest version. I double checked it: `demos/config.ru` exists!

Could you also write a shot 'How-To' about the usage with `node.js`, because I don't have any experience with `node.js`?

**Comment by gdoteof** [comment]
same problem

**Comment by ghost** [comment]
> same problem

gem install thin
